<!-- a Vue component consists of a template, a Vue 'class' (script), and style -->
<template>
  <div class="mpl">
    <ul class="mpl-list">
      <!-- recommended to split mutli-attrib tags over multiple lines -->
      <li
        v-for="k in kickers"
        :key="k.id">
          {{k.name}} - {{k.stat}}
       </li>
    </ul>
    <!--
      kebab-case is recommended in dom templates because works better with html case insensitivity,
      but kebab-case will match with PascalCase-named registered components too.
      An empty element is recommended (eg <player-line></player-line>) as it indicates the element does/will
      have content ... unless being compiled by babel+webpack, which can sort this out for you.
     -->
    <player-line/>
  </div>
</template>

<script>
// import local components
import PlayerLine from './PlayerLine.vue'

// export a default object from this file... ES6
export default {
  // register local components
  components: {
    'player-line': PlayerLine
  },

  // same as data: function()... ES6
  data () {
    return {
      kickers: [
        {
          id: 1,
          name: 'jo',
          stat: 16.8
        },
        {
          id: 2,
          name: 'jen',
          stat: 15.3
        }
      ]
    }
  }
}
</script>

<!--
  All styles are added globally to the rendered html head tag.

  With 'scoped' the style gets applied only to elements in this component.
  It does this by adding a unique data attribute to all elements generated by this component
  and using that in the style selector.  This is the recommended approach (except for root components).

  Witout scoped all styles just get added to the page with no data selector, and so last in wins.

  It is recommened to NOT use element selectors (eg button) with scoped, use class selectors (eg .btn_thing).
-->
<style scoped lang="scss">
.mpl {
  background-color: blue;
}

ul.mpl-list {
  display: flex;
  flex-wrap: wrap;
  list-style-type: none;
  padding: 0;
}

ul.mpl-list li {
  flex-grow: 1;
  flex-basis: 200px;
  padding: 1px;
  border: thin black solid;
}
</style>
